# Generated by Django 4.1.7 on 2023-02-25 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import musics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.PositiveSmallIntegerField(choices=[(6, 'Funk'), (0, 'Other'), (5, 'Country'), (4, 'Soul'), (2, 'Rock'), (10, 'Blues'), (7, 'Folk'), (1, 'Hip hop'), (12, 'Pop'), (3, 'Rhythm and blues'), (11, 'Classical'), (8, 'Disco'), (9, 'Electronic')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='')),
                ('released', models.DateField(blank=True, null=True)),
                ('single_by', models.CharField(blank=True, max_length=64)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('sample', models.FileField(blank=True, null=True, upload_to='samples', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav']), musics.validators.MaxFileSizeValidator(max_size=10485760)])),
                ('extras', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='', max_length=500)),
                ('stars', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('musics', models.ManyToManyField(related_name='artists', to='musics.music')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('musics', models.ManyToManyField(related_name='albums', to='musics.music')),
            ],
        ),
    ]
