# Generated by Django 4.1.7 on 2023-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Pop'), (2, 'Rock'), (8, 'Disco'), (5, 'Country'), (4, 'Soul'), (10, 'Blues'), (7, 'Folk'), (1, 'Hip hop'), (6, 'Funk'), (9, 'Electronic'), (0, 'Other'), (3, 'Rhythm and blues'), (11, 'Classical')], default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
