# Generated by Django 4.1.7 on 2023-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_rename_name_album_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Pop'), (3, 'Rhythm and blues'), (7, 'Folk'), (2, 'Rock'), (1, 'Hip hop'), (5, 'Country'), (4, 'Soul'), (6, 'Funk'), (8, 'Disco'), (9, 'Electronic'), (11, 'Classical'), (10, 'Blues'), (0, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
