# Generated by Django 4.1.7 on 2023-02-25 17:38

import django.core.validators
from django.db import migrations, models
import musics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_additionalinfo_genre_alter_album_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='sample_sampled',
            field=models.FileField(blank=True, null=True, upload_to='samples/sampled', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav']), musics.validators.MaxFileSizeValidator(max_size=10485760)]),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hip hop'), (4, 'Soul'), (3, 'Rhythm and blues'), (9, 'Electronic'), (2, 'Rock'), (5, 'Country'), (11, 'Classical'), (6, 'Funk'), (12, 'Pop'), (10, 'Blues'), (0, 'Other'), (8, 'Disco'), (7, 'Folk')], default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
