# Generated by Django 4.1.7 on 2023-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_remove_music_sample_sampled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Rhythm and blues'), (10, 'Blues'), (5, 'Country'), (0, 'Other'), (2, 'Rock'), (7, 'Folk'), (12, 'Pop'), (1, 'Hip hop'), (4, 'Soul'), (11, 'Classical'), (6, 'Funk'), (8, 'Disco'), (9, 'Electronic')], default=0),
        ),
    ]
