# Generated by Django 4.1.7 on 2023-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (4, 'Drama'), (3, 'Sci-Fi'), (2, 'Comedy'), (0, 'Action')], default=0),
        ),
    ]
