# Generated by Django 4.1.7 on 2023-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_additionalinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (3, 'Sci-Fi'), (0, 'Action'), (4, 'Drama'), (2, 'Comedy')], default=0),
        ),
    ]
