# Generated by Django 4.1.7 on 2023-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_additionalinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-Fi'), (4, 'Drama'), (1, 'Horror'), (0, 'Action'), (2, 'Comedy')], default=0),
        ),
    ]
