# Generated by Django 4.1.7 on 2023-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_additionalinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-Fi'), (1, 'Horror'), (2, 'Comedy'), (0, 'Action'), (4, 'Drama')], default=0),
        ),
    ]
