# Generated by Django 4.1.7 on 2023-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_additionalinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (4, 'Drama'), (3, 'Sci-Fi'), (0, 'Action'), (2, 'Comedy')], default=0),
        ),
    ]
